crates/shared/src/config.rs
crates/spyglass/src/api/route.rs
crates/tauri/src/cmd.rs
crates/tauri/src/constants.rs
crates/tauri/src/main.rs
crates/tauri/src/rpc.rs
crates/tauri/src/window.rs
crates/tauri/tauri.conf.json

- Fixes #3
- Fixes #6, tauri just recently updated their build CLI
- Some refactoring & cleanup to the tauri crate
- Updates stats in tray menu correctly on non-macos distros

Fix for "Show ... folder crash" and general improvements

---

README.md
crates/shared/src/config.rs
crates/tauri/src/constants.rs
crates/tauri/src/main.rs

* Fixes #9 
* Add a table of contents to the docs
* Add docs for configurable shortcut settings

Configurable shortcut

---

.github/workflows/publish.yml
.github/workflows/rust.yml
Cargo.lock
crates/tauri/Cargo.toml
crates/tauri/tauri.conf.json

* Switching to YYYY.MM.DD versioning for app for my own sanity
* Bumping tauri version + adding missing feature for system tray

Bumping versions for 2022.4.27 release

---

.github/workflows/rust.yml
Cargo.lock
crates/shared/src/config.rs
crates/spyglass/src/state.rs
crates/tauri/Cargo.toml
crates/tauri/src/rpc.rs

Fixing startup crash with large limits

---

crates/client/Cargo.toml
crates/client/src/main.rs

- FIxes #16 
- Force focus on search box when UI is displayed

Fix cursor moving during selection + focus on show

---

crates/client/public/glue.js
crates/client/src/main.rs
crates/tauri/src/cmd.rs
crates/tauri/src/window.rs

Workaround for Windows freeze bug

---

crates/client/public/glue.js
crates/client/src/events.rs
crates/client/src/main.rs
crates/tauri/src/window.rs

- Fixes search box not being focus sometimes when the bar is shown.
- Fixes "Tab" causing the search box to lose focus.

Better focus handling

---

.github/workflows/publish.yml
README.md

Fix doc examples

---

crates/tauri/src/main.rs
crates/tauri/src/menu.rs

Manual searchbar activation

---

Cargo.lock
crates/client/src/constants.rs
crates/client/src/events.rs
crates/client/src/main.rs
crates/spyglass/src/search/query.rs
crates/tauri/Cargo.toml
crates/tauri/src/main.rs
crates/tauri/src/menu.rs

- Closes #28 
- Fixes issue where crawler stats in menu is not updated on linux

Linux bugfixes

---

crates/client/src/components.rs
crates/shared/src/config.rs
crates/spyglass/src/task.rs
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs
crates/tauri/src/rpc.rs

- Add some better logging in case sidecar terminates.
- Attempt to restart backend if IPC comms are lost (should help w/ #39)

Gracefully handle crawler crash

---

README.md
crates/entities/src/models/mod.rs
crates/entities/src/test.rs
crates/reindexer/src/main.rs
crates/shared/src/config.rs
crates/spyglass/src/importer.rs
crates/spyglass/src/main.rs
crates/spyglass/src/state.rs
crates/tauri/src/main.rs

Closes #40 
Adding a new `data_directory` setting to let users configure where to store their index

Add setting to configure data directory

---

crates/spyglass/src/task.rs

Fix high CPU usage on pause

---

Cargo.lock
crates/client/src/pages/stats.rs
crates/entities/src/models/bootstrap_queue.rs
crates/entities/src/models/lens.rs
crates/entities/src/models/mod.rs
crates/entities/src/test.rs
crates/migrations/src/lib.rs
crates/migrations/src/m20220522_000001_bootstrap_queue_table.rs
crates/shared/src/config.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/main.rs
crates/spyglass/src/scraper/element.rs
crates/spyglass/src/search/lens.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/search/query.rs
crates/spyglass/src/task.rs
crates/tauri/Cargo.toml

Detect new/updated lenses w/o full app restart

---

Cargo.lock
crates/entities/src/models/crawl_queue.rs
crates/tauri/Cargo.toml
crates/tauri/src/constants.rs
crates/tauri/src/main.rs
crates/tauri/src/menu.rs

Update version menu item with a link to the new release

New version check

---

crates/client/public/main.css
crates/tauri/tauri.conf.json

Bumping version number for v2022.5.26 release

v2022.5.26 release

---

crates/spyglass/src/search/lens.rs

Now that we have a way for folks to find & download lenses built in, we don't need to create a default lens

Remove default lens creator

---

crates/entities/src/models/crawl_queue.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/fetch.rs
crates/spyglass/src/importer.rs
crates/spyglass/src/main.rs
crates/spyglass/src/search/lens.rs
crates/tauri/src/cmd.rs

Dearest Reviewer,
I got the firefox import working. A few changes include:
All log statements have a prefix
Firefox has its own lens to allow all domains
batch fetch in flight domains
batch insert urls
remove unwrap on url methods
Becker

large-import-batches

---

.github/workflows/rust.yml
Cargo.lock
Makefile
crates/tauri/Cargo.toml
crates/tauri/tauri.conf.json

Bumping to latest stable tauri release

⬆️ bump to tauri v1.0.0

---

.github/workflows/publish.yml
.github/workflows/rust.yml
crates/tauri/tauri.conf.json

Setting up macos code signing so that new users don't get that annoying pop-up on first launch

ci(macos): enabling macOS code signing

---

crates/client/public/glue.js
crates/client/public/main.css
crates/client/src/components/btn.rs
crates/client/src/main.rs
crates/client/src/pages/stats.rs
crates/shared/src/rpc.rs
crates/spyglass/src/api/mod.rs
crates/spyglass/src/api/route.rs
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs

feature: recrawl button for domains in crawler status page

---

.github/workflows/publish.yml
Makefile
crates/tauri/tauri.conf.json

validating release flow works w/ plugins

ci: release workflow w/ plugins

---

crates/client/public/glue.js
crates/client/public/main.css
crates/client/src/components/btn.rs
crates/client/src/main.rs
crates/client/src/pages/stats.rs
crates/shared/src/rpc.rs
crates/spyglass/src/api/mod.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/main.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/state.rs
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs
plugins/chrome-importer/src/main.rs
plugins/firefox-importer/src/main.rs

Closes #115 and fixes some bugs w/ plugins

feat: clear queue button + bugfixes

---

crates/spyglass/src/crawler/robots.rs
crates/tauri/Cargo.toml
crates/tauri/tauri.conf.json

bugfix: windows install issues

---

crates/spyglass/src/crawler/mod.rs

`https://xkcd.com/1375` would be treated as a different url than `https://xkcd.com/1375` despite being 301 redirected to it.

bugfix: properly handle 301 redirects during crawling

---

Cargo.lock
crates/spyglass/Cargo.toml
crates/tauri/tauri.conf.json

release v2022.7.4

---

crates/spyglass/src/fetch.rs
crates/tauri/Cargo.toml
crates/tauri/src/main.rs
crates/tauri/src/rpc.rs
crates/tauri/src/window.rs

- Adding in support for error dialogs
- Refactoring some unwrap usage in `tauri`
- Better error handling w/ sidecar, HTTP client

feature: error dialogs

---

crates/spyglass/src/api/route.rs

Indexed documents were not being deleted from the SQLite DB due to a missing `.await` on the seaorm delete call. I've added this, and split the index deletion into it's own scope since the mutex guard blocks the await call.
**Note** - I've moved the `writer.commit()` call into the loop, so this now gets called every time a document is deleted from the index. I don't know what the performance implications of this are, so I figured I'd mention it for consideration.

Fix indexed documents not being deleted from DB

---

crates/shared/src/regex.rs

hotfix: escape wildcard characters for DB matches

---

assets/plugins/chrome-importer/manifest.ron
assets/plugins/firefox-importer/manifest.ron
assets/plugins/local-file-indexer/manifest.ron
crates/client/public/fixtures.js
crates/client/public/main.css
crates/client/src/pages/settings.rs
crates/shared/src/config.rs
crates/shared/src/lib.rs
crates/shared/src/plugin.rs
crates/spyglass/src/main.rs
crates/spyglass/src/plugin/mod.rs
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs
crates/tauri/src/rpc.rs

Allow user to update plugin settings from UI

feature: plugin settings management

---

Cargo.lock
Makefile
crates/entities/src/models/crawl_queue.rs
crates/spyglass-plugin/src/consts.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/api/route.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/fetch.rs
crates/spyglass/src/plugin/exports.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/search/lens.rs
plugins/local-file-indexer/src/main.rs

- combine 429 & http failure check
- correctly handle URLs from plugins enqueue
- pull hostname for local file importer
- sort plugins by name

bugfix: bugfix galore

---

assets/plugins/chrome-importer/manifest.ron
assets/plugins/firefox-importer/manifest.ron
assets/plugins/local-file-indexer/manifest.ron
crates/client/src/components/btn.rs
crates/client/src/components/mod.rs
crates/client/src/main.rs
crates/client/src/pages/admin.rs
crates/client/src/pages/crawl_stats.rs
crates/client/src/pages/lens_manager.rs
crates/client/src/pages/plugin_manager.rs
crates/client/src/pages/settings.rs
crates/client/src/pages/updater.rs
crates/client/src/utils.rs
crates/entities/src/models/bootstrap_queue.rs
crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/fetch_history.rs
crates/entities/src/models/indexed_document.rs
crates/entities/src/models/lens.rs
crates/entities/src/models/link.rs
crates/entities/src/models/resource_rule.rs
crates/shared/src/form.rs
crates/shared/src/lib.rs
crates/shared/src/plugin.rs
crates/shared/src/regex.rs
crates/shared/src/response.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/fetch.rs
crates/tauri/src/cmd.rs
plugins/firefox-importer/src/main.rs

- Fix Windows firefox/chrome data folder path serialization issues
- Validate & alert user to errors when saving settings
- Cleaning up retry logic in HTTPClient
- Quick bugfix to close #161

bugfix: handle path serialization issues in settings

---

crates/shared/src/form.rs
crates/tauri/src/cmd.rs

- Checks for the existence of the path(s) & alerts the user if something is wrong
- Tweak so we don't unnecessarily save & restart the app if nothing has been change.

feature: validate setting paths

---

crates/tauri/installer/windows/main.wxs
crates/tauri/tauri.conf.json

installer(windows): Allow user to choose install directory

---

.github/workflows/publish.yml

Add support for universal binaries so that ARM macs don't run that digusting intel code ever again.

ci(macos): target universal builds for macOS compatibility

---

crates/spyglass/src/main.rs
crates/spyglass/src/task.rs

bugfix: pause bootstrap w/ spyglass is paused

---

crates/client/public/fixtures.js
crates/client/src/pages/startup.rs
crates/migrations/src/m20220823_000001_migrate_search_schema.rs
crates/migrations/src/utils/migration_utils.rs
crates/shared/src/event.rs
crates/spyglass/src/crawler/mod.rs
crates/tauri/src/plugins/startup.rs

- Add in more checks for index schema migration.
- Better startup progress reporting. Long migrations now doesn't seem like something is frozen.
- Failures during migration will be reported to user (who will hopefully report the bug).

bugfix: startup progress window + bugfixes

---

plugins/firefox-importer/src/main.rs

bugfix: periodically sync Firefox db file instead of just on-load

---

crates/entities/src/models/crawl_queue.rs
crates/migrations/src/lib.rs
crates/migrations/src/m20220823_000001_migrate_search_schema.rs
crates/migrations/src/m20220917_000001_add_col_to_queue.rs
crates/shared/src/config.rs
crates/spyglass-lens/src/lib.rs
crates/spyglass-lens/src/pipeline.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/lib.rs
crates/spyglass/src/main.rs
crates/spyglass/src/pipeline/collector.rs
crates/spyglass/src/pipeline/default_pipeline.rs
crates/spyglass/src/pipeline/mod.rs
crates/spyglass/src/pipeline/parser.rs
crates/spyglass/src/plugin/exports.rs
crates/spyglass/src/search/grouping.rs
crates/spyglass/src/search/lens.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/state.rs
crates/spyglass/src/task.rs

Adds in basic pipeline support. This simple update allows a lens to use a pipeline instead of normal url collection and processing. Currently the pipeline does not provide any additional functionality and is a placeholder to expand features on top of.

Pipeline Initial Checkin

---

crates/client/public/main.css
crates/client/src/components/icons.rs
crates/client/src/main.rs
crates/client/src/pages/admin.rs
crates/client/src/pages/crawl_stats.rs
crates/migrations/src/utils/migration_utils.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/state.rs
crates/tauri/src/main.rs
crates/tauri/src/plugins/startup.rs
crates/tauri/src/rpc.rs

- Move wizard popup until after successful backend connection is established.
- Pop-up alert if we're unable to connect to search backend even after retrying several times.

bugfix: alert user on backend startup errors

---

Cargo.lock
crates/client/public/fixtures.js
crates/client/src/components/icons.rs
crates/client/src/pages/lens_manager.rs
crates/client/src/utils.rs
crates/entities/src/models/crawl_queue.rs
crates/shared/src/event.rs
crates/shared/src/response.rs
crates/spyglass-lens/Cargo.toml
crates/spyglass-lens/src/lib.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/search/lens.rs
crates/tauri/src/cmd.rs
crates/tauri/src/constants.rs
crates/tauri/src/main.rs
crates/tauri/src/plugins/lens_updater.rs
crates/tauri/src/plugins/mod.rs
crates/tauri/src/plugins/startup.rs

feature: check for updated lenses & update to newer version

---

crates/client/index.html
crates/client/public/main.css
crates/client/src/pages/search.rs
crates/client/src/pages/startup.rs
crates/tauri/Cargo.toml
crates/tauri/src/main.rs
crates/tauri/tauri.conf.json

Just for fun. Those sharp edges were really killing me 🙂.
Also a little exploration of how theming would work.

tweak(ui): trying out rounded corners on macOS & win11

---

Cargo.lock
crates/tauri/Cargo.toml
crates/tauri/src/main.rs

- auto-launch: `0.2.0` -> `0.4.0`
- open: `2` -> `3`

deps: bumping `auto-launch` & `open` to latest versions

---

crates/spyglass/src/pipeline/default_pipeline.rs
crates/spyglass/src/pipeline/mod.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/task.rs

- 😴 sleep more in task manager event loop 
- 😴 sleep more in the plugin event loop

bugfix: fixing some extra CPU usage w/ plugin event & manager event loop

---

Cargo.lock
crates/spyglass/Cargo.toml
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/lib.rs
crates/spyglass/src/main.rs
crates/spyglass/src/parser/docx_parser.rs
crates/spyglass/src/parser/mod.rs
crates/spyglass/src/pipeline/mod.rs

Adds support for reading and indexing docx files. To support this feature two new repos have been added. docx-rs provides the docx features and has been updated to handle modern docx format. hard-xml has been added with modifications to support the docx namespace requirements.

Initial update to add .docx parse support

---

Cargo.lock
crates/spyglass/Cargo.toml
crates/spyglass/src/parser/mod.rs
crates/spyglass/src/parser/xlsx_parser.rs

Added parser for xlsx, xls and ods files. This builds on top of the docx support.

xlsx, xls, and ods parser support

---

Cargo.lock
crates/client/src/pages/search.rs
crates/spyglass-plugin/src/shims.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/plugin/exports.rs
crates/spyglass/src/plugin/mod.rs
plugins/firefox-importer/src/main.rs

- fix: Windows path compatibility for firefox import plugin
- fix: default Windows Firefox data dir detection
- fix: bookmark parsing logic

bugfix: firefox plugin windows compatibility

---

crates/spyglass/src/plugin/mod.rs

- fixes `bookmarks` lens hanging waiting for plugin response

bugfix: fix lock contention w/ plugin manager

---

crates/spyglass/src/crawler/mod.rs

- Handles pages that don't have a set `canonical` meta tag set.
- Closes #231

bugfix: extract URL from web.archive.org link if there is no canonical url tag

---

Cargo.lock
crates/tauri/Cargo.toml
crates/tauri/src/main.rs
crates/tauri/src/platform/mac.rs

Properly handle macOS dock events without polling

tweak: expose & handle RunEvent::ApplicationShouldHandleReopen

---

crates/spyglass-plugin/src/consts.rs
crates/spyglass/src/plugin/exports.rs
crates/spyglass/src/plugin/mod.rs

takes into account ignore files when watching for file changes for crawling/indexing

bugfix: handle ignore on file changes

---

crates/tauri/src/main.rs

Fixed an issue where auto-launch toggle would turn on when toggled but not turn off

bugfix: check autolaunch toggle & enable/disable accordingly

---

crates/entities/src/models/tag.rs
crates/migrations/src/m20220823_000001_migrate_search_schema.rs
crates/migrations/src/m20221115_000001_local_file_pathfix.rs
crates/migrations/src/utils/migration_utils.rs
crates/shared/src/form.rs
crates/shared/src/regex.rs
crates/spyglass-lens/src/lib.rs
crates/spyglass-lens/src/utils.rs
crates/spyglass-plugin/src/shims.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/crawler/client.rs
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/parser/docx_parser.rs
crates/spyglass/src/parser/mod.rs
crates/spyglass/src/parser/xlsx_parser.rs
crates/spyglass/src/plugin/exports.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/scraper/element.rs
crates/spyglass/src/task/worker.rs

Fix Clippy errors
1. Inline vars for format strings
2. Missing await usage

Cleanup Clippy errors

---

crates/client/src/components/lens.rs

- Update link to use - instead of _
- Add view details link to discover page

Update View Details Link

---

Cargo.lock
crates/shared/src/response.rs
crates/spyglass/Cargo.toml
crates/tauri/tauri.conf.json

Prepping for v2023.1.1 release

release: v2023.1.1

---

Cargo.lock
crates/tauri/Cargo.toml
crates/tauri/src/main.rs
crates/tauri/src/plugins/startup.rs
crates/tauri/src/rpc.rs
crates/tauri/src/window.rs

- Move main window creation code into `windows` module for consistency
- Fixes bug on Windows where closing the searchbar window causes events expecting the window to fail

bugfix: gracefully handle closed window events

---

crates/client/src/components/lens.rs
crates/client/src/pages/discover.rs
crates/entities/src/lib.rs
crates/entities/src/models/connection.rs
crates/shared/src/response.rs
crates/spyglass/src/api/mod.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/connection/gcal.rs
crates/spyglass/src/connection/gdrive.rs
crates/spyglass/src/connection/github.rs
crates/spyglass/src/connection/mod.rs
crates/spyglass/src/filesystem/mod.rs
crates/spyglass/src/filesystem/utils.rs

Updates the My Library tab to include install information for the local filesystem

Add filesystem to library tab

---

crates/client/src/components/result.rs
crates/entities/src/models/connection.rs
crates/migrations/src/lib.rs
crates/migrations/src/m20230131_000001_add_is_syncing_to_connection_table.rs
crates/spyglass/src/connection/gcal.rs
crates/spyglass/src/connection/gdrive.rs
crates/spyglass/src/connection/github.rs
crates/spyglass/src/task.rs

- fix shortened windows paths in search results
- add column to connection table to keep track of sync status
- set sync status in gdrive/gcal/github connections

tweak: windows path tweaks & update google conns

---

Cargo.lock
crates/spyglass/Cargo.toml

fix incorrect API id returned from google client

bugfix: bump third party api libs

---

crates/migrations/src/lib.rs
crates/migrations/src/m20230201_000001_add_tag_index.rs
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/search/query.rs

- Identify any tags that match search tokens and add those tags as possible search results

Add tags to search

---

Cargo.lock
crates/spyglass/Cargo.toml
crates/spyglass/src/connection/github.rs

GitHub will fail silently if we don't check for 401 errors & handle accordingly

tweaks: handle OAuth failures during syncs

---

crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/indexed_document.rs
crates/spyglass/src/search/mod.rs

Setting the batch size to something well below: [SQLITE_LIMIT_VARIABLE_NUMBER](https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitvariablenumber)

bugfix: chunk deletions from index/db

---

Cargo.lock
crates/client/public/fixtures.js
crates/client/public/glue.js
crates/client/src/main.rs
crates/client/src/pages/search.rs
crates/shared/src/event.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/task.rs
crates/tauri/src/cmd.rs

- tweak: Show an error message if we're unable to open a link/file for some reason
- bugfix: Spawn `configure_watcher` as a new task when called in the manager

tweak: show error on open error

---

Cargo.lock
crates/client/src/components/btn.rs
crates/spyglass/src/connection/mod.rs
crates/spyglass/src/lib.rs
crates/spyglass/src/platform/mod.rs
crates/tauri/Cargo.toml
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs
crates/tauri/src/platform/linux.rs
crates/tauri/src/platform/mac.rs
crates/tauri/src/platform/windows.rs
crates/tauri/src/window.rs

- Fix #333 - Use `current_binary` from tauri to get the correct path for the autolauncher.
- Fix #332 - Fix path issues when running `xdg-open` inside an AppImage
- Fix #187 - Binaries should be built w/ executable flag set
- #135 closed due to fix [tauri/4915](https://github.com/tauri-apps/tauri/issues/4915)
- Fix #133 - Use screen size + scale + window size to position window in the middle of screen
- Also fixes resizing issues on linux

bugfix: various AppImage & linux issues

---

crates/client/src/components/result.rs
crates/shared/src/request.rs
crates/spyglass-rpc/src/lib.rs
crates/spyglass/src/api/handler/mod.rs
crates/spyglass/src/api/mod.rs

For users with thousands of bookmarks 😮

tweak: add batch webext sync

---

crates/client/src/components/user_action_list.rs
crates/entities/src/models/processed_files.rs
crates/spyglass/src/filesystem/mod.rs
crates/spyglass/src/filesystem/utils.rs
crates/spyglass/src/task.rs

- use chrono for SystemTime conversion
- chunk processed file deletion
- add explicit check for remove all
- bump up wait interval for scheduler during busy sessions

bugfix: last modified time conversion

---

Cargo.lock
crates/spyglass-rpc/Cargo.toml
crates/spyglass-rpc/src/lib.rs
crates/spyglass/src/api/handler/mod.rs
crates/spyglass/src/api/mod.rs
crates/spyglass/src/connection/mod.rs
crates/spyglass/src/pipeline/cache_pipeline.rs
crates/spyglass/src/state.rs
crates/spyglass/src/task.rs
crates/tauri/Cargo.toml
crates/tauri/src/main.rs
crates/tauri/src/plugins/lens_updater.rs
crates/tauri/src/plugins/mod.rs
crates/tauri/src/plugins/notify.rs
crates/tauri/src/plugins/startup.rs
crates/tauri/src/rpc.rs
crates/tauri/src/window.rs

feature: notify user when lens install/connection syncs are complete

---

crates/spyglass/src/documents/mod.rs
crates/spyglass/src/filesystem/audio.rs

whisper expects mono audio samples

bugfix: convert stereo audio to mono before transcription

---

Cargo.lock
crates/shared/src/metrics.rs
crates/tauri/Cargo.toml
crates/tauri/Info.plist
crates/tauri/src/main.rs

Support for custom app URL schemes. Will enable us to install lenses directly from the lens website.

feature: deep linking

---

crates/entities/src/schema.rs
crates/migrations/src/m20230315_000001_migrate_search_schema.rs
crates/spyglass/src/debug/main.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/search/query.rs

WIP: Update tokenizer 

---

Cargo.lock
crates/client/src/components/user_action_list.rs
crates/shared/src/config.rs
crates/shared/src/config/user_actions.rs
crates/tauri/src/cmd.rs
crates/tauri/src/platform/mac.rs

- Adds `Open parent folder` action for files
- Also adds in an `OpenUrl` action

tweak: add open parent folder action to defaults

---

crates/entities/src/models/indexed_document.rs
crates/spyglass/src/documents/mod.rs

- For a large # of files, the deletion process chokes up when deleting files from `tantivy`

bugfix: file index deletion issue

---

README.md
VERSION.json
scripts/upload-version.py

Updating VERSION.json & README.md links

chore: release v2023.4.1

---

Cargo.lock
crates/spyglass/Cargo.toml

- Closes #452 
- Update reddit library to use new auth requirements

bugfix: reddit integration

---

apps/web/src/client.rs
apps/web/src/components/nav.rs
apps/web/src/main.rs
apps/web/src/pages/landing.rs
apps/web/src/pages/mod.rs
apps/web/src/pages/search.rs

- Center example questions
- Add "Powered by Spyglass" button

tweak(web): cleaning up public lens landing page

---

apps/web/src/client.rs
apps/web/src/components/mod.rs
apps/web/src/components/nav.rs
apps/web/src/main.rs
apps/web/src/pages/dashboard.rs
apps/web/src/pages/lens_editor/add_source.rs
apps/web/src/pages/lens_editor/mod.rs
apps/web/src/pages/mod.rs
crates/ui-components/src/btn.rs
crates/ui-components/src/icons/mod.rs
crates/ui-components/src/results.rs

- Reorganizing sidebar to make room for future search history stuff
- Making add url/podcast/file UI a little friendlier
- Turn source list into a table & show better statuses

polish(web): lens edit UI

---

apps/web/src-css/main.css
apps/web/src/client.rs
apps/web/src/components/chat_bubble.rs
apps/web/src/components/mod.rs
apps/web/src/main.rs
apps/web/src/pages/chat.rs
apps/web/src/pages/embedded.rs
apps/web/src/pages/mod.rs
apps/web/src/pages/search.rs
apps/web/src/schema.rs
apps/web/src/utils.rs

- Added support for embedded routing
- Add initial outline for chat-based search
- Add initial user and theme customization for embedded lenses

Feature embedded chat

---

apps/web/Cargo.toml
apps/web/public/utils.js
apps/web/src/client.rs
apps/web/src/components/file_upload.rs
apps/web/src/components/mod.rs
apps/web/src/main.rs
apps/web/src/pages/lens_editor/add_source.rs
apps/web/src/pages/lens_editor/mod.rs
crates/ui-components/src/icons/mod.rs

Add the ability to add files to a lens by directly uploading the file.

Feature file upload

---

Cargo.lock
crates/spyglass-processor/Cargo.toml
crates/spyglass-processor/src/parser/audio.rs
crates/spyglass/src/crawler/mod.rs

- Update audio processing to handle utf8 characters broken up between two segments

Bugfix skip bad audio

---

crates/spyglass-searcher/src/client/local.rs

Adding additional error messaging for when trying to run backend if there's already a spyglass instance running.

Additional Lockfile Error Message

---

Makefile.toml

Need to use `tauri build` instead of `cargo build` for the app :)

Fix `cargo make` not working on a fresh checkout

---

dockerfiles/api-server.Dockerfile
dockerfiles/web.Dockerfile

fix: Fix Web Container Build

---

.github/workflows/publish.yml
apps/tauri/tauri.rel.conf.json

- Prepping for a new release with the new changes
- May stall do this issue: https://github.com/tauri-apps/tauri-action/issues/941

Refactoring publish workflow for new release

---

.github/workflows/publish.yml

- only tested on windows at the moment

turning off cuda feature for linux builds

---

crates/entities/src/models/mod.rs
crates/entities/src/models/vec_documents.rs
crates/entities/src/models/vec_to_indexed.rs
crates/migrations/src/lib.rs
crates/migrations/src/m20241115_000001_embedding_to_indexed_document.rs
crates/spyglass-model-interface/src/embedding_api.rs
crates/spyglass/src/api/handler/search.rs
crates/spyglass/src/documents/embeddings.rs
crates/spyglass/src/documents/mod.rs

- Update large documents to have multiple embeddings per document

Update Multi embedding

---

apps/desktop-client/src/pages/search/SearchPage.tsx
crates/entities/src/models/vec_documents.rs

- Fix sql query
- Add check for strange selection issue

Bugfix lens search

---

apps/desktop-client/src/pages/bigmode/BigMode.tsx
apps/desktop-client/src/pages/search/SearchPage.tsx
apps/tauri/src/cmd.rs
crates/shared/src/request.rs
crates/spyglass-searcher/src/client/local.rs
crates/spyglass-searcher/src/lib.rs
crates/spyglass/src/api/handler/search.rs

- Add ability to add another page to the results when the last result is selected

Add paging to results

---

crates/entities/src/models/vec_documents.rs
crates/shared/src/config.rs
crates/spyglass-searcher/src/lib.rs
crates/spyglass/bin/debug/src/main.rs

Add basic llm document Q&A to the debug utility

Add document Q&A to the debug utility 
