Makefile

I was getting the following error when building from source:
```
cp target/release/spyglass crates/tauri/binaries/spyglass-server-aarch64-apple-darwin
cp: crates/tauri/binaries/spyglass-server-aarch64-apple-darwin: No such file or directory
make: *** [build-release] Error 1
```
Creating the dir before copying solves the issue. Tested by building in a clean clone.

Create cp destination dir before copying

---

crates/tauri/src/window.rs

IMO current_monitor is a bit misleading as it uses the current monitor
the app is in, not the current monitor the user interacts with.
This is not optimal in a multi-monitor setup, as you often end
up with spyglass on the monitor that is not your primary. primary_monitor
on the other hand uses, you guessed it, the primary monitor, which I
see as more logical.
The optimal solution would be to get the monitor that the user is
currently interacting with, but this is not trivial.
Also, thanks for creating this awesome project! Looking forward to see the development going forward.

💄 Use primary monitor instead of current

---

crates/client/public/components/_searchbox.scss
crates/client/src/components.rs
crates/entities/src/models/crawl_queue.rs
crates/reindexer/src/main.rs
crates/shared/src/config.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/importer.rs
crates/spyglass/src/main.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/state.rs
crates/spyglass/src/task.rs
crates/tauri/src/window.rs

- Fix filtering on CDX request so we only accept successful crawls.
- Bootstrap lenses async so that startup time is still reasonable.
- Switch to an `enqueue_all` function to add 1000s of urls/links at once vs one-at-a-time.
- Cleaning up results a little bit, splitting up the domain / path to make it easier to read.
- Refactoring mutexes for index & config so that writing doesn't impact reading from the index.

Crawl queue and bootstrap perf optimizations

---

Cargo.lock
README.md
crates/entities/Cargo.toml
crates/entities/src/lib.rs
crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/mod.rs
crates/entities/src/regex.rs
crates/reindexer/src/main.rs
crates/shared/src/config.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/crawler/robots.rs
crates/spyglass/src/importer.rs
crates/spyglass/src/task.rs
crates/tauri/src/main.rs

- By default, only crawl URLs that match rules inside lenses.

Add setting & functionality to only crawl urls specified by lens rules

---

crates/spyglass/src/main.rs
crates/spyglass/src/search/mod.rs

- Calling commit on every `add_document` call is overkill and leads to slower crawls while also causing lock issues
- Spawn a cleanup task to commit every 10s

Index poison error

---

crates/spyglass/src/crawler/mod.rs

Fixes an issue where URLs not normally crawlable would make it through to the index (e.g. the "edit" page of a wiki page)

Crawls for bootstrapped urls should check against the og domain

---

crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/crawler/robots.rs

Paths w/ query args were incorrectly checked during robots.txt rule checks.
For example: `en.wikipedia.org/w/index.php?title=Rust_(programming_language)&action=edit)` would only be checked as `en.wikipedia.org/w/index.php` missing rules that checked for `&action=edit`

🐛 Fix robots.txt check for paths with query args

---

Cargo.lock
crates/entities/Cargo.toml
crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/indexed_document.rs
crates/entities/src/regex.rs
crates/shared/src/config.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/crawler/robots.rs
crates/spyglass/src/search/lens.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/task.rs
fixtures/lens/test.ron

- Add a `rules` param to lenses.
- Rules (for now) only take `SkipURLs` which are minimal regexes that when matching a URL will skip it during a crawl.
Rules are especially useful for skipping over parts of a website that aren't really relevant for a topic. For example, any MediaWiki site, such as`wiki.factorio.com`, has lots of extra MediaWiki specific pages that are technically allowed to be indexed such as User/Talk/Template pages or edit/history pages which might not be useful when searching.

Add support for lens rulesets, starting with `SkipURL`

---

crates/client/public/glue.js
crates/client/public/main.css
crates/client/src/components/btn.rs
crates/client/src/components/mod.rs
crates/client/src/main.rs
crates/client/src/pages/search.rs
crates/shared/src/response.rs
crates/shared/src/rpc.rs
crates/spyglass/src/api/mod.rs
crates/spyglass/src/api/route.rs
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs

Occasionally we'll crawl something that has been 404'd, rather than wait for the crawler to crawl the page again, this adds a little button to each search result to allow users to delete it.
<p align="center">
</p>
- Add space for a future action bar on the right of search results.
- Add a trash can button to delete the document.

Ability to delete indexed documents from search results

---

crates/spyglass/src/search/query.rs

- Boost match for a full string term, i.e "programming language" in title/content.
- Boost match for title of page.
- Move content match back down to normal boost.

Tweak query boosts a little bit

---

Cargo.lock
crates/tauri/Cargo.toml
crates/tauri/src/main.rs

There was an annoying bug where activating the search bar would switch to the space the app was opened in vs moving the window to the active space.

bugfix(macos): Fix swapping spaces on window activation

---

Cargo.lock
crates/entities/src/models/crawl_queue.rs
crates/shared/src/config.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/crawler/robots.rs
crates/spyglass/src/fetch.rs
crates/spyglass/src/lib.rs
crates/spyglass/src/main.rs
crates/spyglass/src/task.rs
crates/tauri/src/main.rs

- Properly handle duplicate URLs when using `enqueue_all`
- No logs while user settings was being loaded
- Handle https -> http fallback for sites that don't support HTTPs, closes #67 
- Basic handling of 429 error codes, closes #68

Bugfixes, https -> http fallback, & more.

---

crates/client/public/glue.js
crates/client/src/main.rs
crates/spyglass/src/crawler/mod.rs
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs

- Closes #52 
- Listen to offline/online events and pause/unpause the crawler accordingly
- Log failures w/ fetching so we can better debug issues

Handle internet outage

---

crates/client/src/pages/search.rs
crates/entities/src/regex.rs

On larger indexes / lenses, sending a search request per character will (naturally) slow down the app.

bugfix(client): debounce search queries

---

crates/tauri/src/constants.rs
crates/tauri/src/main.rs

By default the update check only happens on startup. Since spyglass is meant to run for a very long time, add in a check every 6 hours for an update

updater: trigger update check every 6 hours

---

crates/spyglass/src/crawler/mod.rs

we don't use this for anything at the moment. In the future, we should store this in a cache & refetch if necessary

tweak: save a little space by not storing the entire HTML page in the index

---

crates/spyglass/src/api/route.rs
crates/spyglass/src/crawler/mod.rs
crates/tauri/Cargo.toml

- Clear fetch history for domain on recrawl domain (prevented recrawls from happening if recently fetched).
- Track URL query params as part of fetch history URL

bugfix: correctly track URLs w/ query params in fetch history

---

crates/entities/src/models/bootstrap_queue.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/search/lens.rs

When a domain is deleted from the crawl_status page, it previously wasn't removed from the bootstrap_queue. This means the domain would never be re-bootstrapped, therefore never being indexed again.
This adds a `dequeue()` method to the bootstrap_queue, and dequeues the seed_url as part of the `delete_domain()` call

Delete seed_url during domain deletion

---

crates/tauri/src/main.rs
crates/tauri/src/rpc.rs

On updates / restarts the backend sometimes locks. This manages that interaction better & gracefullly handles termination/restart

bugfix: better handling of sidecar start/restarts

---

crates/shared/src/rpc.rs
crates/spyglass/src/api/mod.rs
crates/spyglass/src/api/route.rs
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs

Closes #63 
- Moves the pause/unpause request off the main UI thread. Will still hold up other RPC requests while the backend processes the request, but shouldn't freeze the UI

bugfix: dont hold up main UI thread on pause/unpause

---

crates/entities/src/models/crawl_queue.rs

fixes reports of duplicates on newly bootstrapped lenses

bugfix: mark bootstrapped tasks as in progress on dequeue

---

.github/workflows/publish.yml
.github/workflows/rust.yml

- Using `ubuntu-latest` has been creating some dependency issues for folks not on the latest release

tweak: use older version of ubuntu image for better linux compatibility

---

Cargo.lock
crates/migrations/Cargo.toml
crates/migrations/src/lib.rs
crates/migrations/src/m20220823_000001_migrate_search_schema.rs
crates/migrations/src/utils/migration_utils.rs
crates/migrations/src/utils/mod.rs

The schema migration process used the standard rename function for replacing the index directories. This function does not work with directories on windows. Created a utility to tar up the old index files and move the new index into place. A conditional compile is used to keep using the rename on non windows os.

Fix issue with windows rename method for directories

---

assets/plugins/chrome-importer/manifest.ron
assets/plugins/firefox-importer/manifest.ron
assets/plugins/local-file-indexer/manifest.ron
crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/lens.rs
crates/entities/src/models/mod.rs
crates/entities/src/schema.rs
crates/entities/src/test.rs
crates/migrations/src/lib.rs
crates/shared/src/config.rs
crates/shared/src/plugin.rs
crates/spyglass-plugin/src/lib.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/main.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/search/lens.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/search/query.rs
crates/spyglass/src/search/utils.rs
crates/spyglass/src/state.rs
crates/spyglass/src/task.rs
crates/tauri/src/plugins/startup.rs
plugins/local-file-indexer/src/main.rs

- Plugins can apply filters to a search. 
- See changes to `crates/spyglass-plugin/src/lib.rs`
- See `local-file-indexer` plugin for an example of how this will work.
- Calls to plugin funcs are run as their own async task (perhaps should just be a whole new thread?)
- Sleep added to plugin event loop to unblock plugin manager lock
- Integrating a custom scorer into the search to apply filters using info outside the search schema. 
- Simplifies search queries and speeds them up for very large lenses w/ lots of regexes.
- Can apply filters to `url`, `title`, content, etc.
- Use metadata from crawling/page analysis as potential filters as well.
- Plugin manager promoted to `AppState` struct & shared amongst all tasks.
- Renaming `shared::lens::Lens` -> `LensConfig` so we don't confuse it …

feature: support for more complex search filters & filters from plugins

---

Cargo.lock
Cargo.toml
crates/shared/Cargo.toml
crates/shared/src/config.rs
crates/spyglass-lens/Cargo.toml
crates/spyglass-lens/README.md
crates/spyglass-lens/src/lib.rs
crates/spyglass-lens/src/utils.rs
crates/spyglass-plugin/Cargo.toml
crates/spyglass-plugin/README.md

- Pulled out useful lens file related data structures into a publishable crate
- Published [`spyglass-plugin`](https://crates.io/crates/spyglass-plugin) (mostly a placeholder for now as we build this out) & [`spyglass-lens`](https://crates.io/crates/spyglass-lens) to crates.io

refactor: Publish `spyglass-plugin` & `spyglass-lens` crates

---

Cargo.lock
crates/spyglass-lens/Cargo.toml
crates/spyglass-lens/src/lib.rs
crates/spyglass-lens/src/utils.rs
crates/spyglass-plugin/Cargo.toml
crates/spyglass-plugin/src/lib.rs
crates/spyglass/src/search/lens.rs
crates/spyglass/src/search/mod.rs
plugins/local-file-indexer/src/main.rs

- Split filters into allowed / skipped, adds support for filtering search results w/ `LensRule::SkipURL`

tweak: take into account skip rules in lens/search filtering

---

Cargo.lock
Cargo.toml
crates/shared/Cargo.toml
crates/shared/src/config.rs
crates/shared/src/lib.rs
crates/shared/src/rpc.rs
crates/spyglass-rpc/Cargo.toml
crates/spyglass-rpc/src/lib.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/api/mod.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/main.rs
crates/spyglass/src/pipeline/mod.rs
crates/tauri/Cargo.toml
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs
crates/tauri/src/plugins/startup.rs
crates/tauri/src/rpc.rs

feature: update rpc backend & prepping for headless server support

---

.github/workflows/publish.yml
.github/workflows/sentry.yml
Cargo.lock
Makefile
crates/tauri/Cargo.toml
crates/tauri/src/main.rs
crates/tauri/src/plugins/lens_updater.rs
crates/tauri/src/plugins/startup.rs
crates/tauri/src/rpc.rs

- bumping tauri dependencies to `1.1`
- fixes critical dependabot issues w/ `windows` crate 
- send shutdown msg to long running tasks to gracefully exit

bugfix/tweak: consolidate app shutdown logic in client

---

Cargo.lock
assets/plugins/local-file-indexer/manifest.ron
crates/client/src/pages/settings.rs
crates/shared/src/form.rs
crates/spyglass-plugin/Cargo.toml
crates/spyglass-plugin/src/lib.rs
crates/spyglass-plugin/src/shims.rs
crates/spyglass-plugin/src/utils.rs
crates/spyglass/src/plugin/exports.rs
crates/spyglass/src/plugin/mod.rs
plugins/local-file-indexer/Cargo.toml
plugins/local-file-indexer/src/main.rs

Saner defaults & moved the heavy lifting from plugin to core.
- Initial walk & enqueue will take into account `.gitgnore`'s and will walk directories in parallel.
- Watching file updates is now a little smarter.
- User can configure supported file types.

feature: smarter file indexer

---

crates/migrations/src/m20221023_000001_connection_table.rs
crates/spyglass/src/connection/mod.rs
crates/spyglass/src/main.rs
crates/spyglass/src/task.rs
crates/spyglass/src/task/worker.rs

- bugfix: remove null constraint from refresh token & only update if we are sent a new one.
- refactor: move index commit task into main event loop & keep track of new/updated docs

tweak: index commit task cleanup

---

crates/tauri/src/cmd.rs
plugins/firefox-importer/src/main.rs

- fix for default windows firefox path (slashes facing the wrong way 🤦‍♂️).
- fix for saving plugin settings if user settings are empty/default.

bugfix: firefox importer paths & plugin settings save issue

---

crates/spyglass/src/api/route.rs
crates/spyglass/src/search/mod.rs
crates/spyglass/src/search/query.rs

Search queries now use the tokenizer for the specific field to identify the search tokens. Phrase search is now used and boosted relative to the number of tokens in the query.

Update search query to use field tokenizer

---

crates/migrations/src/lib.rs
crates/migrations/src/m20221116_000001_add_connection_constraint.rs
crates/spyglass/src/api/route.rs

- add a constraint to the db to only allow one unique `(account, api_id)` combo

bugfix: only allow a single account per connection

---

crates/tauri/src/menu.rs

tweak: update settings menu to remove "Manage" prefix. More concise 🙂

---

crates/entities/src/models/crawl_queue.rs
crates/migrations/src/lib.rs
crates/migrations/src/m20221118_000001_fix_queued_enum.rs
crates/spyglass/src/api/route.rs

- update enum usage in code
- add migration to fix existing dbs

bugfix: sea-orm update caused `Queued` to be quoted inside db

---

crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/main.rs
crates/spyglass/src/pipeline/default_pipeline.rs
crates/spyglass/src/pipeline/mod.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/state.rs
crates/spyglass/src/task.rs
crates/spyglass/src/task/worker.rs

Fixes an issue where during long bootstrapping events the backend can continue existing after shutdown is requested.

bugfix: add bootstrap shutdown listener

---

crates/client/src/components/btn.rs
crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/sql/dequeue.sqlx
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/crawler/robots.rs
crates/spyglass/src/pipeline/default_pipeline.rs
crates/spyglass/src/pipeline/mod.rs
crates/spyglass/src/task.rs
crates/spyglass/src/task/manager.rs
crates/spyglass/src/task/worker.rs

- Spyglass will recrawl files & check for updates (or deletions) on a regular interval. ~once a day for now.
- Cleaned up logic around dequeuing jobs. FIFO: prioritizing bootstraps -> normal crawls -> recrawls.
Crawler changes
- keep track of the canonical URL and removes any duplicate tasks.
- only retry Timeout errors, everything else is marked as failed and we move on.

feature: regular recrawls & dequeue logic cleanup

---

crates/client/src/pages/search.rs
crates/tauri/src/main.rs

Fixes a regression where the search bar will stick around on Windows/Linux despite losing focus. This uses a more platform agnostic way to detect window focus & hide the window

bugfix: hide window when it loses focus

---

crates/client/src/pages/search.rs
crates/tauri/src/main.rs

Windows: prevents a scrollbar from showing up when the app is first started

tweak(windows): add borders to search bar initial inner_size

---

Cargo.lock
crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/crawl_tag.rs
crates/entities/src/models/indexed_document.rs
crates/entities/src/models/mod.rs
crates/entities/src/models/tag.rs
crates/entities/src/test.rs
crates/migrations/Cargo.toml
crates/migrations/src/lib.rs
crates/migrations/src/m20221124_000001_add_tags_for_existing_lenses.rs
crates/migrations/src/m20221210_000001_add_crawl_tags_table.rs
crates/spyglass/src/task.rs
crates/spyglass/src/task/worker.rs

- use transactions + update/insert many to speed up tag migration
- break task tags into their own table vs using a JSON column

tweak: speed up tag migration

---

.github/workflows/rust.yml
Cargo.lock
crates/shared/src/config.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/crawler/robots.rs
crates/spyglass/src/main.rs
crates/spyglass/src/plugin/exports.rs

- Adds basic CLI flag support via `clap` crate
- Runs through basic backend startup & migration checks during CI to catch any startup errors/issues

ci: run & check migrations during CI

---

crates/client/src/components/forms/stringlist.rs

resolves #232 
Code:
Simply tests if the input value is blank
If it is, display an error message as a placeholder (making sure to reset that error message if the user adds a file extension)
If it is not, simply follow the old method of adding the extension to the list

Fix blank local file type

---

crates/entities/src/models/crawl_queue.rs
crates/entities/src/models/indexed_document.rs
crates/entities/src/models/lens.rs
crates/migrations/src/lib.rs
crates/migrations/src/m20230104_000001_add_column_n_index.rs
crates/shared/src/config.rs
crates/spyglass-lens/src/lib.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/crawler/archive.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/crawler/cache.rs
crates/spyglass/src/crawler/mod.rs
crates/spyglass/src/main.rs
crates/spyglass/src/pipeline/cache_pipeline.rs
crates/spyglass/src/pipeline/default_pipeline.rs
crates/spyglass/src/pipeline/mod.rs
crates/spyglass/src/pipeline/parser.rs
crates/spyglass/src/search/lens.rs
crates/spyglass/src/task.rs
crates/spyglass/src/task/worker.rs

Update to lens bootstrapping to branch processing between "remote" and "local" lens files. Remote lens will now check for index caches to bootstrap local index instead of crawling. Local lens will continue to crawl as normal.

Cache load support

---

crates/entities/src/models/indexed_document.rs
crates/spyglass/src/crawler/bootstrap.rs
crates/spyglass/src/pipeline/cache_pipeline.rs
crates/spyglass/src/pipeline/default_pipeline.rs
crates/spyglass/src/pipeline/mod.rs

Lens cache processing has been updated to tag the documents after being added. Currently the documents are only tagged with their associated lens.

Addition of cache tagging

---

crates/client/public/fixtures.js
crates/client/public/glue.js
crates/client/src/components/forms/mod.rs
crates/client/src/components/icons.rs
crates/client/src/components/result.rs
crates/client/src/main.rs
crates/client/src/pages/connection_manager.rs
crates/client/src/pages/crawl_stats.rs
crates/client/src/pages/lens_manager.rs
crates/client/src/pages/plugin_manager.rs
crates/client/src/pages/search.rs
crates/client/src/pages/wizard.rs
crates/entities/src/models/lens.rs
crates/migrations/src/lib.rs
crates/migrations/src/m20230111_000001_add_lens_column.rs
crates/shared/src/constants.rs
crates/spyglass-rpc/src/lib.rs
crates/spyglass/src/api/mod.rs
crates/spyglass/src/api/route.rs
crates/spyglass/src/crawler/cache.rs
crates/spyglass/src/main.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/search/lens.rs
crates/tauri/src/cmd.rs
crates/tauri/src/constants.rs
crates/tauri/src/main.rs
crates/tauri/src/plugins/lens_updater.rs
plugins/chrome-importer/src/main.rs
plugins/firefox-importer/src/main.rs
plugins/local-file-indexer/src/main.rs

- Client lens updater modified to send lens install request to the server
- Lens table updated to include a remote url column and hash column
- Lens is now checked on the server side to detect changes before bootstrapping

tweak: Change lens updater to send requests to server

---

Cargo.lock
crates/client/src/pages/search.rs
crates/entities/src/lib.rs
crates/spyglass-rpc/Cargo.toml
crates/spyglass/Cargo.toml
crates/spyglass/src/api/mod.rs
crates/spyglass/src/main.rs
crates/tauri/Cargo.toml

- Optimize library stats SQL and move out of searchbar until we have a faster (cached?) version.
- add a search in progress indicator
- bump jsonrpsee version

tweak: fixing slow search times due to `get_library_stats`

---

crates/entities/src/lib.rs
crates/shared/src/response.rs
crates/spyglass/src/api/route.rs

- Closes #254.
- Better support for older browsers that don't support that.

bugfix: don't use 64-bit sized ints so wasm-bindgen doesn't generate BigInt64Arrays

---

Cargo.toml
Makefile

tweak cargo build settings for sentry profile to get it to build properly on windows

ci: fix sentry build windows

---

crates/client/public/fixtures.js
crates/client/src/components/icons.rs
crates/client/src/components/result.rs
crates/entities/src/lib.rs
crates/entities/src/models/crawl_queue.rs
crates/migrations/src/m20221124_000001_add_tags_for_existing_lenses.rs
crates/migrations/src/m20221210_000001_add_crawl_tags_table.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/documents/mod.rs
crates/spyglass/src/filesystem/mod.rs
crates/spyglass/src/filesystem/utils.rs

- Use a folder icon for directories in search results.
- Shorten file path shown in result if too long.
- Ignore `.DS_Store` files during local file indexing
- Use `macos_fsevent` instead of `macos_kqueue` feature in notify crate
- Fix: Use open_url in document update

tweak: macos fs update fixes

---

crates/migrations/src/lib.rs
crates/migrations/src/m20230203_000001_add_indexed_document_index.rs

Adding the doc id index on the indexed document table speeds up search speeds on larger data sets

Add index to indexed document on doc id

---

crates/spyglass/src/api/route.rs

Client already handles long descriptions to this is superfluous

bugfix: truncate fails on some unicode characters

---

crates/shared/src/regex.rs
crates/spyglass/src/api/route.rs
crates/tauri/src/menu.rs

Also fixes macos shortcuts for text manip (Cmd+A, etc.)

bugfix: escape special characters in URL prefixes used in a regex

---

crates/spyglass/src/crawler/robots.rs
crates/spyglass/src/filesystem/mod.rs
crates/spyglass/src/filesystem/utils.rs
crates/spyglass/src/pipeline/mod.rs
crates/spyglass/src/scraper/mod.rs

Can cause a panic if it's unable to convert the file URI to a path

bugfix: gracefully handle `uri_to_path` errors 

---

crates/spyglass/src/documents/mod.rs
crates/spyglass/src/search/lens.rs

- Also add a check for empty docs before running `process_crawl_results`

tweak: change log error! -> warn! for lens deserialization issues

---

crates/client/src/pages/wizard/mod.rs

Changing button labels in the wizard to be just `Next`, got some feedback that its a little confusing about what they do

tweak: make next labels in the wizard less confusing

---

crates/spyglass/src/task.rs
crates/spyglass/src/task/manager.rs

This was causing some tasks to wait one after another instead of executing in parallel

bugfix: remove awaits in the worker flow

---

Cargo.lock
crates/entities/src/models/crawl_queue.rs
crates/spyglass/Cargo.toml
crates/spyglass/src/filesystem/mod.rs
crates/spyglass/src/main.rs
crates/spyglass/src/plugin/mod.rs
crates/spyglass/src/task.rs
crates/spyglass/src/task/manager.rs

- Integrating `tokio-console` into our code to make debugging tasks a lot easier (behind a feature flag)
- Fixing some orphaned spawns
- Start & manager  FS watcher task in manager task
- Remove recrawl job check (all handled by FS watcher code now)

bugfix: filesystem watcher CPU usage

---

crates/spyglass/src/api/handler/search.rs

This is mainly for large documents where generating the highlighted term preview may take a while or generates more matches than we need/

bugfix: constrain number of tokens we scan/need before generating a preview

---

crates/client/src/components/user_action_list.rs
crates/client/src/pages/search.rs
crates/client/src/utils.rs
crates/shared/src/accelerator.rs
crates/shared/src/config.rs
crates/shared/src/lib.rs

Update Client OS handling to use specialized OS utility instead of rust config flags. This change is due to the fact that the os target for the client is wasm and not a specific OS

Bugfix Client OS

---

LICENSE

In order to provide more protection (and future support) for our work while ensuring open source access, we're switching over to the AGPL license.

Update License to AGPL

---

VERSION.json
crates/shared/src/metrics.rs
crates/spyglass/src/search/lens.rs
crates/tauri/src/constants.rs
crates/tauri/src/plugins/lens_updater.rs

- Reduce check interval to daily
- Find and remove old lens file before adding new update
- Separate install/update metrics

bugfix: lens updater check

---

crates/spyglass/src/api/handler/mod.rs

- Show total number of paths scanned & don't consider ourselves syncing if there is nothing enqueued

tweak file system syncing stats

---

VERSION.json
crates/tauri/entitlements.plist
crates/tauri/src/rpc.rs

Now that we're using websockets, the connection retry should be when we create the client

bugfix: move retry connection to when we build the client

---

Cargo.lock
crates/entities/Cargo.toml
crates/entities/src/models/mod.rs
crates/entities/src/models/schema/mod.rs
crates/entities/src/models/schema/v1.rs
crates/entities/src/models/schema/v2.rs
crates/entities/src/models/schema/v3.rs
crates/migrations/Cargo.toml
crates/migrations/src/lib.rs
crates/migrations/src/m20220823_000001_migrate_search_schema.rs
crates/migrations/src/m20230112_000001_migrate_search_schema.rs
crates/migrations/src/m20230315_000001_migrate_search_schema.rs
crates/spyglass/Cargo.toml

[x] Update from tantivy 0.18 to 0.19
[x] Add index migration to convert 0.18 compatible index to 0.19 compatible index
[x] Add in new date fields to the index schema, (published, lastmodified)

Update tantivy to 0.19 and add migration

---

crates/spyglass/src/state.rs

shouldn't affect prod, but easy fix nonetheless

tweak: make sure we have receivers before sending an event

---

Cargo.lock
crates/tauri/Cargo.toml
crates/tauri/src/cmd.rs
crates/tauri/src/main.rs
crates/tauri/src/platform/linux.rs
crates/tauri/src/platform/mac.rs
crates/tauri/src/platform/mod.rs
crates/tauri/src/platform/windows.rs
crates/tauri/src/plugins/startup.rs
crates/tauri/src/window.rs

- Using the hotkey while spyglass is open will close it (like Spotlight on macOS)
- Fix an issue where the searchbar is not recentered after alt-tabbing away

tweak: toggle hide/show w/ hotkey & recenter window on resize

---

crates/client/src/pages/search.rs

The action status is set then unset before it can be displayed on the client. Added a short timeout to allow the display to render long enough to view.

Action status is not shown when action is executed

---

crates/spyglass-searcher/src/lib.rs
crates/spyglass/bin/debug/src/main.rs
crates/spyglass/src/api/handler/search.rs
crates/spyglass/src/documents/mod.rs
crates/spyglass/src/plugin/exports.rs

Cleans up the superfluous DocAddr -> Document conversions that were happening outside of the searcher module

tweak: update searcher to return Document struct instead of doc addr

---

crates/spyglass-processor/src/parser/audio.rs

- Fixes issue where non-english audio gets translated to english which is neat but not intended.

tweak: always transcribe audio to original language

---

apps/web/src/pages/landing.rs

Update iframe link to use modest branding and only show videos that are related to the account the original video was published from (spyglass only)

Update iframe link properties

---

crates/shared/src/config.rs
crates/tauri/src/cmd/settings.rs
crates/tauri/src/main.rs
crates/tauri/src/window.rs

Closes #408
This PR adds an option to close the search bar instead of hiding it.
A few things to note:
- On Windows, when the search bar is built using `window::get_searchbar()`, the `platform::is_visible()` function returns `true` (because `lpwndpl.showCmd == SHOW_WINDOW_CMD(1)` apparently). So, I had to remove the ability to close the search bar using the "open search bar shortcut" when the close search bar setting is on. This could probably be avoided by using the [is_minimized()](https://docs.rs/tauri/1.3.0/tauri/window/struct.Window.html#method.is_minimized) method introduced in tauri v1.3.0.
- The setting requires a restart, because I did not wanted to fight against the lifetime that comes with the addition of `settings` to the `shortcuts.register()` closure (see …

feat: add option to close search bar

---

Makefile

When going through the documentation of a new, initial dev setup, there are some errors where some of the env variables are not setup and Tauri app crashes to build because the /dist folder doesn't exist. 
Adding additional checks to see if the file/folder exists for dev setup, if not, then create:
- copying .env.template as an .env file if it doesn't exist
- within setup-dev, make sure Tauri's /dist folder exists before building Tauri app

Include .env file and /dist folder within setup-dev

---

Makefile
crates/tauri/tauri.dev.conf.json

In the case that a dev has a local instance of Spyglass running and a Prod instance, they're both named the same app name, "Spyglass".
These changes will make it that the local instance will now be called "Spyglass Dev" to differentiate the two instances.

Rename app to "Spyglass Dev" for dev instance

---

Makefile

- adding `build-backend` to the `setup-dev` command to copy binaries to Tauri and not run the `build-release` command
- new command to run backend server to make the "building from source" documentation consistent to only using `make` commands
Updating docs to reflect these changes here: https://github.com/spyglass-search/docs.spyglass.fyi/pull/6

 Simplify Backend Commands

---

Makefile.toml

Adding a new file makefile.toml as an alternative to Makefile. 
The next step is properly complete and test on Windows, but wanted to keep this as an intro PR that at least works on macOS.
1. Install [cargo-make](https://github.com/sagiegurari/cargo-make):
`cargo install cargo-make`
2. Setup: `cargo make setup`
3. Run: `cargo make run`
- client only: `cargo make run-client`
- backend only: `cargo make run-backend`
**Note:** will work on the plugin and bundling commands in a future PR.
Here is a separate PR that will update the dev documentations: https://github.com/spyglass-search/docs.spyglass.fyi/pull/6

Add Makefile.toml

---

Cargo.lock
Makefile.toml
crates/spyglass/Cargo.toml

1) There was a typo/copy paste error preventing spyglass from building locally using `cargo-make` on Windows
2) Spyglass failed to compile as-is on current versions of Rust without updating deps, but one dependency was not SemVer-pinned and broke when updated so I pinned it.
3) The build profile was mostly hardcoded to `debug`; changed it to use `CARGO_MAKE_CARGO_PROFILE` where applicable.

Fix a couple of issues preventing `cargo-make` from working on Windows

---

apps/tauri/src/cmd/settings.rs
crates/entities/src/models/embedding_queue.rs
crates/entities/src/models/indexed_document.rs
crates/entities/src/models/vec_documents.rs
crates/shared/src/config.rs
crates/shared/src/config/embeddings.rs
crates/spyglass-model-interface/src/lib.rs
crates/spyglass/src/api/handler/search.rs
crates/spyglass/src/documents/embeddings.rs
crates/spyglass/src/documents/mod.rs
crates/spyglass/src/state.rs
crates/spyglass/src/task.rs

- Add embedding enable / disable to the settings page
- Auto download the model if needed when embeddings are enabled
- When enabled auto add all indexed documents that have not had embeddings generated to the embedding queue
- Update embedding api to be swapable, this allows the model to be reloaded after download

Embedding enable disable

---

crates/entities/src/models/vec_documents.rs

- Bug fix for accessing topx context
- Add method to access all context for a document (with distance)

Vec documents updates
